### ISSUE TITLE
Keil5.18 - Cannot compile SVD

### ISSUE THREAD

**Issue by alexrayne** [StartMilandr/Pack_VEx#5]
Подскажите как побороть этот егог на keil 5.18
```Cannot install Pack Milandr.MDR1986BExx.1.4.2: Cannot compile SVD file(s)```

**Comment by StartMilandr** [comment]
В официальной версии 1.5 поправили эту ошибку. Опечатка вроде там была в pdsc файле с VE - BE для какого-то микроконтроллера.
