### ISSUE TITLE
Централизация библиотеки поддержки периферии

### ISSUE THREAD

**Issue by eldarkg** [StartMilandr/Pack_VEx#6]
Здравствуйте. Есть предложение на внесение изменений из библиотеки https://github.com/eldarkg/emdr1986x-std-per-lib в вашу библиотеку с целью централизации библиотеки. После чего поддержка указанной библиотеки будет приостановленна и библиотека будет помечена как устаревшая.
Также хотелось бы отделить документацию и примеры от исходного кода библиотеки как это сделано здесь:
https://github.com/eldarkg/emdr1986x-std-per-lib
https://github.com/eldarkg/emdr1986x-std-per-lib-doc

**Comment by StartMilandr** [comment]
Здравствуйте. Предложение хорошее, но мы не планируем поддерживать эту библиотеку, взамен нее пишем свою, надеюсь более удобную.  Этот репозиторий является лишь клоном официального пака с исправлениями ошибок с которыми мы столкнулись. Иногда исправления приходят от техподдержки.

**Comment by eldarkg** [comment]
@StartMilandr Мы - это кто? Новая библиотека доступна в общем доступе? Если нет, то когда будет?

**Comment by StartMilandr** [comment]
Мы это небольшой коллектив, при кафедре электротехники. Проект развивается в основном усилиями студентов и для студентов, желающих получить практические знания для дальнейшего успешного трудоустройства, в том числе и в Миландр, где уже работают некоторые наши выпусники, что позволяет нам пользоваться некоторым инсайдом. От библиотеки мы хотим максимального упрощения, чтобы обучать работе интерфейсов (Uart, SPI, PWM...), а не переключению бит в конкретном микроконтроллере конкретного производителя. Изучение внутреннего устройства периферии занимает слишком много времени, а с учетом что она везде разная, то настроить что-либо правильно - вообще катастрофа. Мы хотим скрыть всю настройку внутри более высокоуровневых функций, это полезнее нам для обучения, но слишком крупно для профессионалов.  Поэтому наша библиотека вряд-ли будет полезна тем, кто уже освоил текущую версию и привык в ней работать.

Описание будет тут:
https://startmilandr.ru/doku.php/prog:pack_v6

Если через пол года получится что-нибудь осмысленное, то надеемся на ревью профессионалов с форума. Если проект покажется кому-то полезным, будем вносить правки с учетом выдвинутых замечаний.
